In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("labled.csv")
df.head(3)

,Unnamed: 0,address,name_ru,rating,rubrics,text,is_grocery,id,len,product_quality,staff_service,queues_checkout,assortment_availability,store_cleanliness,other_problem
0,0,"Краснодарский край, Сочи, жилой район Адлер, у...",Черемушки,2,Супермаркет;Магазин продуктов,Самый неопрятный магазин.Еще и тараканы бегают,True,74,46,False,False,False,False,True,False
1,1,"Свердловская область, Екатеринбург, улица Чере...",Магнит косметик,2,Магазин продуктов;Магазин хозтоваров и бытовой...,Вместо мегамарта открыли очередной Магнит. Всё...,True,935,508,False,False,True,False,False,True
2,2,"Московская область, Раменский городской округ,...",Дикси,1,Супермаркет;Магазин продуктов,"Отвратительный магазин, кассы не удобные и оче...",True,960,130,False,True,True,False,False,False

In [4]:
df.drop(columns=["Unnamed: 0", "address", "rubrics", "is_grocery"], inplace=True)
df.head(3)

,name_ru,rating,text,id,len,product_quality,staff_service,queues_checkout,assortment_availability,store_cleanliness,other_problem
0,Черемушки,2,Самый неопрятный магазин.Еще и тараканы бегают,74,46,False,False,False,False,True,False
1,Магнит косметик,2,Вместо мегамарта открыли очередной Магнит. Всё...,935,508,False,False,True,False,False,True
2,Дикси,1,"Отвратительный магазин, кассы не удобные и оче...",960,130,False,True,True,False,False,False

In [5]:
categories = [
    "product_quality",
    "staff_service",
    "queues_checkout",
    "assortment_availability",
    "store_cleanliness",
    "other_problem",
]
for category in categories:
    v = df[category].value_counts()
    f = v.loc[False]
    t = v.loc[True]
    print(f"Category: {category}, count: {t}, percent: {t/(f+t)}")

Category: product_quality, count: 743, percent: 0.3383424408014572
Category: staff_service, count: 1199, percent: 0.5459927140255009
Category: queues_checkout, count: 421, percent: 0.19171220400728597
Category: assortment_availability, count: 305, percent: 0.1388888888888889
Category: store_cleanliness, count: 292, percent: 0.13296903460837886
Category: other_problem, count: 843, percent: 0.383879781420765

In [6]:
pd.set_option("display.max_colwidth", 300)
df[df["other_problem"]]["text"]

1       Вместо мегамарта открыли очередной Магнит. Всё,как везде. Вечно очередь стоит,так как работает 1 кассир,остальные полки загружают. Понятно,дефицит кадров. Столкнулась с привычной историей- несоответствие цены на ценнике и цены на кассе. Взяла масло подсолнечное по акции: 79.9 руб. А на кассе 149...
3       Добрый вечер! Зачем ваши сотрудники втюхивают, что не нужно. Пришёл в ваш магазин, взял что мне нужно. Взял водку Тундра 309,89 руб. Они мне настоятельно порекомендовали другую водку Сенега или Пенега. Я только покупаю на спирту "альфа". Продавцы тоже сказали это водка тоже "альфа". Ну и взял в ...
4                                                                                                                                                                                           Постоянно ценники не соответствуют цене на кассе. Часто надо смотреть цену на приборе, т.к.нет ценника,а это не удобно.
6                                      Их постоянно обкрадывают на икру, вешаешь 100 грам, её сразу уносят на кассу, если орут чья то как то стыдно, когда молча уносят можно на кассе ее забыть если много чего другого купил, или тебе кассир маркетолог зубы заговорит рекламой консерв с осетрами, капец короче
13      Продавцы в отделе хозтоваров абсолютно не знают законы, связанные с их непосредственной деятельностью. Отказывают в продаже товара по цене на ценнике, если цена на кассе выше. Плюс, а точнее жирный минус в том, что ценники на товар очень мелкие и разглядеть что-то можно только вблизи, а цены и н...
                                                                                                                                                           ...
2160    27.03.23 Приобретала продукты на кассе оплатила, у кассира не вышел чек, зависла программа. У меня прошла оплата, я позвонила в Банк мне подтвердили что транзакция прошла. Продавцы мне не отдали продукты, а сказали ещё раз оплачивать. Они так же позвонили директору Палкиной С. А. она так же сказ...
2169    Магазинчик так себе... На Петухова, 156.\nСегодня нагрубили моей маме (72 года).\nГрубиянкой выступила сама заведующая магазином (так она себя назвала) судя по чеку \nБОЛГОВА ЕКАТЕРИНА ВИКТОРОВНА. \nЦен нет, на кассе пробивают другую цену, конечно же в пользу магазина!!!\nНа вопрос: "почему цена...
2170                                                                                                                                                                                                                      Живём рядом ,но ходим другие ближайшие магазины ,в этот очень редко .Цены космос на все !
2185    Не все так однозначно....🤦\nПочему две звёзды при отличном ассортименте,удобной парковке, обилием покупательских корзин,удобном графике работы?!?!?!\nВнимательно относитесь к работе кассиров! В чеке пробивают лишние позиции,т.е. товары,которые не покупала! Наблюдайте за кассирами:\n1. Сидят спин...
2190    Очень плохое расположение магазина.Машины носятся около ступенек,зимой боишься там ходить и выходить из магазина. Нужно запрещать там проезд транспорта или делать вход в магазин с другой стороны. Ничего не посыпается зимой,скользко. Из-за этого тоже большой минус магазину, как пожилым людям там ...
Name: text, Length: 843, dtype: str

In [7]:
main_categories = categories.copy()
main_categories.pop(-1)

'other_problem'

In [8]:
other_only = df[df["other_problem"] & ~df[main_categories].any(axis=1)]
len(other_only)

239

In [9]:
other_only["name_ru"].value_counts()

name_ru
Магнит             30
Красное&Белое      27
Продукты           20
Дикси              16
Перекрёсток        11
                   ..
Центрторг           1
Магнит Моя цена     1
Аппетит             1
Верный              1
Лавка у дома        1
Name: count, Length: 113, dtype: int64

In [10]:
df["other_problem"] = df["other_problem"] & ~df[main_categories].any(axis=1)
df.head(10)

,name_ru,rating,text,id,len,product_quality,staff_service,queues_checkout,assortment_availability,store_cleanliness,other_problem
0,Черемушки,2,Самый неопрятный магазин.Еще и тараканы бегают,74,46,False,False,False,False,True,False
1,Магнит косметик,2,"Вместо мегамарта открыли очередной Магнит. Всё,как везде. Вечно очередь стоит,так как работает 1 кассир,остальные полки загружают. Понятно,дефицит кадров. Столкнулась с привычной историей- несоответствие цены на ценнике и цены на кассе. Взяла масло подсолнечное по акции: 79.9 руб. А на кассе 149...",935,508,False,False,True,False,False,False
2,Дикси,1,"Отвратительный магазин, кассы не удобные и очень маленькие + тесные, касиры хамовитые, мясяца 3 у них небыло ни корзин не тележек.",960,130,False,True,True,False,False,False
3,Красное&Белое,2,"Добрый вечер! Зачем ваши сотрудники втюхивают, что не нужно. Пришёл в ваш магазин, взял что мне нужно. Взял водку Тундра 309,89 руб. Они мне настоятельно порекомендовали другую водку Сенега или Пенега. Я только покупаю на спирту ""альфа"". Продавцы тоже сказали это водка тоже ""альфа"". Ну и взял в ...",1178,731,False,True,False,False,False,False
4,Дикси,1,"Постоянно ценники не соответствуют цене на кассе. Часто надо смотреть цену на приборе, т.к.нет ценника,а это не удобно.",1263,119,False,False,False,False,False,True
5,Бисквит,1,"Купили «Красный бархат» 29 апреля в 17:00 на улице Нахимова. Торт не соответствует своим заявленным качествам. Не сладкий. Коржи странные и странного цвета. Крем точно не натуральный сливочный крем. Праздник был испорчен. Ужасное качество. При этом готовы купить и дороже, заехали так как было уд...",2012,310,True,False,False,False,False,False
6,Дары моря,1,"Их постоянно обкрадывают на икру, вешаешь 100 грам, её сразу уносят на кассу, если орут чья то как то стыдно, когда молча уносят можно на кассе ее забыть если много чего другого купил, или тебе кассир маркетолог зубы заговорит рекламой консерв с осетрами, капец короче",2077,268,False,False,False,False,False,True
7,Ладоград,2,"В этот магазин ходила за продуктами с самого его открытия, живу в пешей доступности. Всем его рекомендовала.\nНо в последнее время частенько не могу туда попасть. Закрываются за 15- 20 минут до 21-00, причем перед самым носом. Подходишь к магазину, оттуда продавщицы с сигаретами выходят, закрыв...",2202,812,False,True,False,False,False,False
8,Микей,2,"Качество продуктов и чистота в магазине радуют, но вот эти временные продавцы, которые приходят в магазин на 1-2 дня это ужас. Набирают хрен пойми откуда. Недавно покупала прокладки и мне довольно молодой кассир, на вид лет 18-20 заявил, что мне должно было быть стыдно покупать одни прокладки и ...",2280,595,False,True,False,False,False,False
9,Величество трапеза,1,"Купил сегодня в магазине ""Тройка"" пельмени ""Татарские"" мало того что пельмени оказались слегка изувеченые при лепке но и вкус оказался еще тот. Тесто местами толстое и жесткое. Дату производства не нашел. Срок годности не нашел. Покупаем полуфобрикаты крайне редко в виду особеностей ребенка и ба...",2532,513,True,False,False,False,False,False

In [11]:
for category in categories:
    v = df[category].value_counts()
    f = v.loc[False]
    t = v.loc[True]
    print(f"Category: {category}, count: {t}, percent: {t/(f+t)}")

Category: product_quality, count: 743, percent: 0.3383424408014572
Category: staff_service, count: 1199, percent: 0.5459927140255009
Category: queues_checkout, count: 421, percent: 0.19171220400728597
Category: assortment_availability, count: 305, percent: 0.1388888888888889
Category: store_cleanliness, count: 292, percent: 0.13296903460837886
Category: other_problem, count: 239, percent: 0.10883424408014572

In [12]:
df["n_labels"] = df[categories].sum(axis=1)
print(df["n_labels"].value_counts())
df["n_labels"].describe()

n_labels
1    1325
2     598
3     181
0      59
4      30
5       3
Name: count, dtype: int64

count    2196.000000
mean        1.456740
std         0.751882
min         0.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         5.000000
Name: n_labels, dtype: float64

In [13]:
df.head(5)

,name_ru,rating,text,id,len,product_quality,staff_service,queues_checkout,assortment_availability,store_cleanliness,other_problem,n_labels
0,Черемушки,2,Самый неопрятный магазин.Еще и тараканы бегают,74,46,False,False,False,False,True,False,1
1,Магнит косметик,2,"Вместо мегамарта открыли очередной Магнит. Всё,как везде. Вечно очередь стоит,так как работает 1 кассир,остальные полки загружают. Понятно,дефицит кадров. Столкнулась с привычной историей- несоответствие цены на ценнике и цены на кассе. Взяла масло подсолнечное по акции: 79.9 руб. А на кассе 149...",935,508,False,False,True,False,False,False,1
2,Дикси,1,"Отвратительный магазин, кассы не удобные и очень маленькие + тесные, касиры хамовитые, мясяца 3 у них небыло ни корзин не тележек.",960,130,False,True,True,False,False,False,2
3,Красное&Белое,2,"Добрый вечер! Зачем ваши сотрудники втюхивают, что не нужно. Пришёл в ваш магазин, взял что мне нужно. Взял водку Тундра 309,89 руб. Они мне настоятельно порекомендовали другую водку Сенега или Пенега. Я только покупаю на спирту ""альфа"". Продавцы тоже сказали это водка тоже ""альфа"". Ну и взял в ...",1178,731,False,True,False,False,False,False,1
4,Дикси,1,"Постоянно ценники не соответствуют цене на кассе. Часто надо смотреть цену на приборе, т.к.нет ценника,а это не удобно.",1263,119,False,False,False,False,False,True,1

In [14]:
df.drop(columns=["name_ru", "rating", "len", "n_labels"], inplace=True)
df.head(3)

,text,id,product_quality,staff_service,queues_checkout,assortment_availability,store_cleanliness,other_problem
0,Самый неопрятный магазин.Еще и тараканы бегают,74,False,False,False,False,True,False
1,"Вместо мегамарта открыли очередной Магнит. Всё,как везде. Вечно очередь стоит,так как работает 1 кассир,остальные полки загружают. Понятно,дефицит кадров. Столкнулась с привычной историей- несоответствие цены на ценнике и цены на кассе. Взяла масло подсолнечное по акции: 79.9 руб. А на кассе 149...",935,False,False,True,False,False,False
2,"Отвратительный магазин, кассы не удобные и очень маленькие + тесные, касиры хамовитые, мясяца 3 у них небыло ни корзин не тележек.",960,False,True,True,False,False,False

In [18]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(df, test_size=0.3, random_state=42, shuffle=True)

val_df, test_df = train_test_split(
    temp_df, test_size=0.5, random_state=42, shuffle=True
)

train_df.to_csv("train.csv", index=False)
test_df.to_csv("test.csv", index=False)
val_df.to_csv("valid.csv", index=False)